version: '2'
services:
    app:
        build:
            context: .
            dockerfile: ./dev.Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./app:/var/www/app:cached
            - ./app/vendor:/var/www/app/vendor:cached
            - /var/www/app/var/cache
            - /var/www/app/var/logs
            - /var/www/app/var/sessions
            - ./docker:/var/www/docker
            - ./docker/php-app.ini:/etc/php7/conf.d/99_custom_app.ini
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/s6/fpm:/etc/s6/fpm/run
            - ./docker/s6/nginx:/etc/s6/nginx/run
        environment:
            APP_ENV: dev
